/**
 * Created by kiettv on 1/3/17.
 */
import * as express from "express";
import advertisers from "./advertiser/advertiser.router";
import advertisingTemplate from "./advertising_template/advertising_template.router";
import announcement from "./announcement/announcement.router";
import auth from "./auth/auth.router";
import banUser from "./ban_users/ban_user.router";
import bookings from "./bookings/booking.router";
import clustering from "./clustering/clustering.router";
import condo from "./condo/condo.router";
import condorules from "./condo_rules/condo_rules.router";
import contract from "./contract/contract.router";
import councilminutes from "./council_minutes/council_minutes.router";
import facilities from "./facilities/facilities.router";
import feedback from "./feedback/feedback.router";
import feeds from "./feeds/feed.router";
import functionPassword from "./function_password/function_password.router";
import garageSale from "./garage_sale/garage_sale.router";
import getQuotation from "./get_quotation/get_quotation.router";
import health from "./health/health.router";
import housingloan from "./housing_loan/housing_loan.router";
import latesttransaction from "./latest_transaction/latest_transaction.router";
import me from "./me/me.router";
import media from "./media/media.router";
import moving from "./moving/moving.router";
import onlineform from "./online_form/online_form.router";
import payment from "./payment/payment.router";
import roles from "./roles/roles.router";
import report from "./report/report.router";
import token from "./tokens/tokens.router";
import tool from "./tools/tools.router";
import transactions from "./transaction_hististory/transaction.router";
import usefulContacts from "./useful_contacts/useful_contacts.router";
import userManager from "./user_manager/user_manager.router";
import userUnit from "./user_unit/user_unit.router";
import users from "./users/users.router";
import whaton from "./what_on/what_on.router";
import push from "./push/push.router";
import SellMyCar from "./sell_my_car/sell_my_car.router";
import sendMail from "./send_mail/send_mail.router";
import todo from "./todo/todo.router";
import variable from "./variable/variable.router";

const router = express.Router();

router.use("/advertisers", advertisers);
router.use("/advertising", advertisingTemplate);
router.use("/announcement", announcement);
router.use("/auth", auth);
router.use("/banusers", banUser);
router.use("/bookings", bookings);
router.use("/clustering", clustering);
router.use("/condo", condo);
router.use("/condorules", condorules);
router.use("/contract", contract);
router.use("/councilminutes", councilminutes);
router.use("/facilities", facilities);
router.use("/feedback", feedback);
router.use("/feeds", feeds);
router.use("/functionpassword", functionPassword);
router.use("/garagesale", garageSale);
router.use("/getquotation", getQuotation);
router.use("/health", health);
router.use("/housingloan", housingloan);
router.use("/latesttransaction", latesttransaction);
router.use("/me", me);
router.use("/media", media);
router.use("/moving", moving);
router.use("/onlineform", onlineform);
router.use("/payment", payment);
router.use("/roles", roles);
router.use("/report", report);
router.use("/tokens", token);
router.use("/tools", tool);
router.use("/tools", tool);
router.use("/transactions", transactions);
router.use("/transactions", transactions);
router.use("/usefulcontacts", usefulContacts);
router.use("/user/manager", userManager);
router.use("/users", users);
router.use("/userunit", userUnit);
router.use("/whaton", whaton);
router.use("/push", push);
router.use("/sellmycar", SellMyCar);
router.use("/sendmail", sendMail);
router.use("/todos", todo);
router.use("/variables", variable);

export default router;

