import { MAX_SELL_MY_CAR } from "./constants";
/**
 * Created by kiettv on 10/2/16.
 */
class Code {
    public readonly CODE;
    public readonly MESSAGE;

    constructor(code, message) {
        this.CODE = code;
        this.MESSAGE = message;
    }
}

export const ErrorCode = {
    UNKNOWN: {
        TYPE: "Unknown.",
        GENERIC: new Code(0, "Internal Server Error."),
        NOT_IMPLEMENT: new Code(1, "Not Implement ExceptionModel"),
        UPGRADE_NEEDED: new Code(2, "Please update new version"),
        MAINTENANCE_PERIOD: new Code(3, "Maintenance period"),
        APOCALYPSE: new Code(13, "The world is end"),
    },
    RESOURCE: {
        TYPE: "Resource.",
        GENERIC: new Code(1000, "unknown Resource's Error."),
        INVALID_URL: new Code(1001, "invalid url."),
        NOT_FOUND: new Code(1002, "the item has been deleted"),
        DUPLICATE_RESOURCE: new Code(1003, "resource was already existed."),
        INVALID_REQUEST: new Code(1004, "invalid Request."),
        EMPTY_EMAIL: new Code(1005, "email can't be empty."),
        INVALID_EMAIL: new Code(1006, "invalid email."),
        INVALID_EMAIL_FORMAT: new Code(1006, "invalid email format."),
        INVALID_PASSWORD: new Code(1007, "password must be at least 6 characters."),
        EMAIL_IS_USED: new Code(1008, "email was used."),
        UPDATE_FAILED: new Code(1009, "update resource failed"),
        MISSING_REQUIRED_FIELDS: new Code(1010, "missing required fields."),
        INVALID_PARAMETER: new Code(1011, "invalid parameter."),
        PASSWORD_USE_BEFORE: new Code(1012, "you can't use a password you have used before."),
        INVALID_PHONE_NUMBER: new Code(1013, "the phone number format is incorrect"),
        UNIT_INVALID: new Code(1014, "block / unit does not exist"),
        ROLE_INVALID: new Code(1015, "invalid role"),
        USER_INVALID: new Code(1016, "invalid user"),
        CONDO_NOT_ACTIVE: new Code(1017, "we'll be coming to your condo real soon!\nplease contact your condo manager for more information"),
        UNIT_IN_USE: new Code(1018, "Unit has existing users"),
        USER_HAS_UNIT: new Code(1019, "you are also the owner or tenant of the other unit."),
        FEEDBACK_CATEGORY_INVALID: new Code(1020, "invalid category feedback"),
        ONLINE_FORM_CATEGORY_INVALID: new Code(1021, "invalid category online form"),
        CONDO_CANNOT_MANAGER: new Code(1023, "the condo is being managed by another user"),
        FEEDBACK_INVALID: new Code(1024, "invalid feedback"),
        ANNOUNCEMENT_INVALID: new Code(1025, "invalid announcement"),
        WHAT_ON_INVALID: new Code(1026, "invalid what on"),
        PROOF_OF_RESIDENCE_NOT_FOUND: new Code(1027, "Proof of residence document not found"),
        PRICE_INVALID: new Code(1029, "invalid price"),
        SUMMARY_INVALID: new Code(1030, "invalid summary"),
        FACILITY_TYPE_DOES_NOT_EXIST: new Code(1031, "Facility's type does not exist"),
        FACILITY_DOES_NOT_EXIST: new Code(1032, "Facility does not exist"),
        DURATION_TYPE_DOES_NOT_EXIST: new Code(1033, "Slot's duration type does not exist"),
        SLOT_TIME_OVERLAP: new Code(1034, "Slot's time overlap each others"),
        SLOT_SESSION_OVERLAP: new Code(1035, "Slot's session overlap each others"),
        CATEGORY_NOT_FOUND: new Code(1036, "The category does not exist."),
        FACILITY_OCCUPIED: new Code(1037, "Facility was occupied."),
        ADVERTISER_NOT_FOUND: new Code(1038, "The advertiser does not exist."),
        CONDO_NOT_FOUND: new Code(1039, "The condo does not exist."),
        TEMPLATE_NOT_FOUND: new Code(1040, "The template does not exist."),
        TEMPLATE_NOT_INSIDE_ADVERTISER: new Code(1041, "The template does not inside the advertiser or deleted."),
        BEHIND_ADVANDCE_BOOK_DAYS: new Code(1042, "Your booking date is behind the advance date."),
        GARAGE_SALE_INVALID: new Code(1043, "the garage sale does not exist."),
        FEED_NOT_EXIST: new Code(1045, "the feed does not exist."),
        FEED_TYPE_INVALID: new Code(1046, "invalid feed type."),
        COMMENT_NOT_EXIST: new Code(1047, "the comment does not exist."),
        QUOTA_EXCEED: new Code(1048, "quota exceeded"),
        SLOT_DOES_NOT_EXIST: new Code(1049, "The slot does not exist."),
        NOT_ENOUGH_MONEY_TO_PAY: new Code(1050, "Error! Not enough money to pay this item."),
        SAVE_FAILED: new Code(1051, "Save failed."),
        ITEM_HAS_BEEN_PAID: new Code(1052, "The item has been paid!"),
        REQUEST_QUOTE_FAIL: new Code(1053, "you cannot request a quote. please contact condo manager for more detail"),
        DEPENDENT_USER_CHANGE: new Code(1054, "The dependent info (isResident, tenanctyExpiry) has been changed. Please refresh to update"),
        CLUSTER_NAME_INVALID: new Code(1055, "Cluster's name is invalid"),
        CLUSTER_TYPE_INVALID: new Code(1056, "Cluster's type is invalid"),
        BAN_USER_TYPE_INVALID: new Code(1057, "invalid ban user type."),
        BAN_USER_EXIST: new Code(1058, "the user has already banned."),
        ACCOUNT_IS_BANNED: new Code(1059, "\n\nyour account has been banned\n\nplease contact\nadmin@icondo.asia"),
        SLOT_SUSPENDED: new Code(1060, "Slot was suspended."),
        CAN_NOT_CANCEL: new Code(1061, "Booking can not cancel."),
        CANCEL_DECLINE: new Code(1062, "You can not cancel booking at the moment."),
        MAX_SELL_MY_CAR: new Code(1063, `You can not create more than ${MAX_SELL_MY_CAR} emails.`),
        RATING_TEMPLATE_INVALID_DATA: new Code(1064, `Invalid data.`),
        INVALID_CONDO_NAME: new Code(1065, `Condo name is invalid`),
        INVALID_DATE_TYPE: new Code(1066, "Invalid date type"),
        BOOKING_NOT_FOUND: new Code(1067, "Booking not found"),
        FEEDBACK_CATEGORY_EXIST: new Code(1068, "feedback category was existed"),
        ONLINE_FORM_CATEGORY_TEMPLATE_INVALID: new Code(1069, "invalid category template online form"),
        ONLINE_FORM_SUB_CATEGORY_TEMPLATE_INVALID: new Code(1070, "invalid sub category template online form"),
        ONLINE_FORM_SUB_CATEGORY_NOT_FOUND: new Code(1022, "online form sub category not found"),
        ONLINE_FORM_FEE_INVALID: new Code(1071, "invalid online form price"),
    },
    AUTHENTICATION: {
        TYPE: "Authentication.",
        GENERIC: new Code(1100, "unknown authentication's error."),
        VIOLATE_RFC6750: new Code(1101, "RFC6750 states the access_token MUST NOT be provided in more than one place in a single request."),
        TOKEN_NOT_FOUND: new Code(1102, "token not found."),
        INVALID_AUTHORIZATION_HEADER: new Code(1103, "invalid authorization header."),
        ACCOUNT_NOT_FOUND: new Code(1104, "account not found."),
        WRONG_USER_NAME_OR_PASSWORD: new Code(1105, "wrong user name or password."),
        WRONG_PASSWORD: new Code(1105, "you have entered the wrong password."),
        INVALID_TOKEN: new Code(1106, "invalid token."),
        TOKEN_EXPIRE: new Code(1107, "token expired."),
        NEED_ACCESS_CODE: new Code(1108, "access code is needed."),
        INVALID_CODE: new Code(1109, "invalid access code."),
        ALREADY_ACTIVE: new Code(1110, "account has already activated."),
        NEED_ACTIVE: new Code(1112, "account has not activated."),
        ALREADY_VERIFY_PHONE: new Code(1113, "your phone code already verified. Pls resend new pin code"),
        INVALID_VERIFY_PHONE_CODE: new Code(1114, "the verification code entered is invalid"),
        VERIFY_PHONE_CODE_EXPIRE: new Code(1115, "verify phone code expired."),
        LIMIT_QUOTA: new Code(1116, "you have reached the maximum number of verification limit"),
        SINGLE_LOGGED_IN: new Code(1106, "this account is currently logged on another device \nto use this device, please proceed to the login page"),
    },
    PRIVILEGE: {
        TYPE: "Privilege",
        GENERIC: new Code(1200, "unknown privilege's error."),
        NOT_ALLOW: new Code(1201, "you do not have permission to access."),
        NOT_ALLOW_CONDO_LESS: new Code(1202, "you do not have a condo to access."),
        SUPPORT_ONLY_FOR_RESIDENT_USER: new Code(1203, "you are currently registered as a non resident \nbooking of facilities is only available to condo residents \nplease contact your condo manager for more information \nthank you"),
        INVALID_VERSION: new Code(1204, "invalid version format"),
        VERSION_NOT_FOUND: new Code(1205, "version not found"),
        FORCE_UPDATE: new Code(1206, "please update to the latest version")
    },
    PAYMENT: {
        TYPE: "PAYMENT",
        GENERIC: new Code(1300, "unknown braintree's error."),
        TYPE_PAYMENT_INVALID: new Code(1301, "payment type invalid"),
        PAYMENT_INVALID: new Code(1302, "The payment invalid."),
        WRONG_BILLING_DETAIL: new Code(1303, "Invalid billing detail. Please booking again."),
        MISSING_CUSTOMER_ID: new Code(1304, "Missing customerId"),
        MISSING_PAYMENT_GATEWAY_ACCOUNT: new Code(1305, "Missing condo's payment gateway account"),
        CREATE_CARD_FOR_PAY_BY_CASH: new Code(1036, "Can not create card in pay-by-cash condo"),
        LIST_CARD_FOR_PAY_BY_CASH: new Code(1036, "Can not get list card in pay-by-cash condo"),
        STRIPE_KEY_INVALID: new Code(1308, "Invalid Stripe key"),
        MISSING_CUSTOMER_CARD: new Code(1309, "The credit card transaction has been declined, please contact the resident")
    },
    OPEATION: {
        TYPE: "OPEATION",
        GENERIC: new Code(1400, "Unknown error."),
        FIREBASE_DISABLE: new Code(1401, "Firebase was disable"),
        PAYMENT_DISABLE: new Code(1402, "Payment was disable"),
    }
};
export default ErrorCode;
